# Generated by Django 5.0.6 on 2024-06-21 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('idMedico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('genero', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('telefono', models.CharField(max_length=30)),
                ('especialidad', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Medico',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('idPaciente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('genero', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=30)),
                ('contacto_emergencia', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Paciente',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idRol', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Rol',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('idCita', models.AutoField(primary_key=True, serialize=False)),
                ('fechaCita', models.DateTimeField()),
                ('estado', models.CharField(max_length=20)),
                ('idMedico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionHospital.medico')),
                ('idPaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionHospital.paciente')),
            ],
            options={
                'db_table': 'Cita',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=20)),
                ('contraseña', models.CharField(max_length=20)),
                ('idRol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionHospital.rol')),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
        migrations.AddField(
            model_name='paciente',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionHospital.usuario'),
        ),
        migrations.AddField(
            model_name='medico',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionHospital.usuario'),
        ),
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('idAdministrativo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionHospital.usuario')),
            ],
            options={
                'db_table': 'Administrativo',
            },
        ),
    ]
