# Generated by Django 5.0.6 on 2024-06-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionHospital', '0003_alter_usuario_contraseña'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativo',
            name='dni',
            field=models.CharField(default=14589635, max_length=20),
            preserve_default=False,
        ),
    ]
