# Generated by Django 5.0.6 on 2024-06-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionHospital', '0004_administrativo_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='horarioEntrada',
            field=models.DateTimeField(null=True, blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medico',
            name='horarioSalida',
            field=models.DateTimeField(null=True, blank=True),
            preserve_default=False,
        ),
    ]
