from django.urls import path
from .views import *

urlpatterns = [
    path('getpacientes/',getPacientes , name='getPacientes'),
    path('getmedicos/',getMedicos , name='getMedicos'),
    path('getadministrativos/',getAdministrativos , name='getAdministrativos'),
    path('getUsuarios/',getUsuarios , name='getUsuarios'),
    path('getcitas/',getCitas , name='getCitas'),
    path('postCrearPaciente/', postCrearPaciente, name='crearPaciente'),
    path('registrarMedico/', registrar_Medico, name='registrarMedico'),
    path('registrarAdministrativo/', registrarAdministrativo, name='crearAdministrativo'),
    path('validarDniPaciente/', validar_dni_paciente, name='validardnipaciente'),
    path('buscarmedicosespecialidad/', buscar_medicos_especialidad, name='buscarmedicosespecialidad'),
    path('horariosDisponiblesMedico/', horarios_disponibles_medico, name='horariosdisponiblesmedico'),
    path('buscarPacientePorDni/<str:dni>/', buscar_paciente_por_dni, name='buscarpacientepordni'),
    path('buscarMedicoPorDni/<str:dni>/', buscar_medico_por_dni, name='buscarmedicopordni'),
    path('buscarAdministrativoPorDni/<str:dni>/', buscar_administrativo_por_dni, name='buscaradminpordni'),
    path('crearCita/', crear_cita, name='crearcita'),
    path('login/', login, name='login'),
    path('getAllHistoriales/', getallhistoriales, name='getallhistoriales'),
    path('getHistorialUsuario/', getHistorialUsuario, name='getHistorialUsuario'),
    path('agregarComentarioTratamiento/<str:paciente_id>/<str:tratamiento_id>', agregar_comentario_tratamiento, name='agregar_comentario_tratamiento'),
    path('agregarHospitalizacion/<str:paciente_id>/', agregar_hospitalizacion, name='agregar_hospitalizacion'),
    path('agregarTratamiento/<str:paciente_id>/', agregar_tratamiento, name='agregar_tratamiento'),
    path('agregarhistorialmedicovacio/', agregar_historial_medico_vacio, name='agregar_historial_medico_vacio'),
    path('getAllTratamientos/',get_all_tratamientos, name='get_all_tratamientos'),
    path('getTratamientosByPacienteId/<str:paciente_id>/',get_tratamientos_by_paciente_id, name='get_tratamientos_by_paciente_id'),
    path('getAllHospitalizaciones/',get_all_hospitalizaciones, name='get_all_hospitalizaciones'),
    path('getHospitalizacionesByPacienteId/<str:paciente_id>/',get_hospitalizaciones_by_paciente_id, name='get_hospitalizaciones_by_paciente_id'),
    path('editPaciente/<str:dni>/',editPaciente, name='editPaciente'),
    path('editMedico/<str:dni>/',editMedico, name='editMedico'),
    path('editAdministrativo/<str:dni>/',editAdministrativo, name='editAdministrativo'),
    path('deletePaciente/<str:dni>/',deletePaciente, name='deletePaciente'),
    path('deleteMedico/<str:dni>/',deleteMedico, name='deleteMedico'),
    path('deleteAdministrativo/<str:dni>/',deleteAdministrativo, name='deleteAdministrativo'),
    path('eliminarCita/<int:idCita>/',eliminarCita, name='eliminarCita'),
    path('editarEstadoCita/<int:idCita>/',editarEstadoCita, name='editarEstadoCita'),
]
